# Generated by Django 3.2.7 on 2021-09-13 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_auto_20210913_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='followers',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'followers'},
        ),
    ]
