# Generated by Django 3.2.7 on 2021-09-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20210913_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'posts'},
        ),
    ]
