# Generated by Django 3.2.7 on 2021-09-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_alter_posts_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='profile',
        ),
    ]
